use utoipa::OpenApi;
use guide_core::models::*;
use crate::routes::*;

#[derive(OpenApi)]
#[openapi(
    paths(
        health::health,
        health::version,
        campaigns::list_campaigns,
        campaigns::create_campaign,
        campaigns::get_campaign,
        campaigns::update_campaign,
        campaigns::delete_campaign,
        characters::list_characters,
        characters::create_character,
        characters::get_character,
        characters::update_character,
        characters::delete_character,
        characters::analyze_backstory,
        sessions::list_sessions,
        sessions::create_session,
        sessions::get_session,
        sessions::delete_session,
        sessions::start_session,
        sessions::end_session,
        sessions::list_events,
        sessions::create_event,
        sessions::get_summary,
        sessions::export_summary,
        sessions::get_improv_prompt,
        sessions::generate_debrief,
        encounters::list_encounters,
        encounters::create_encounter,
        encounters::get_encounter,
        encounters::delete_encounter,
        encounters::start_encounter,
        encounters::next_turn,
        encounters::end_encounter,
        encounters::update_participant,
        documents::list_documents,
        documents::upload_document,
        documents::get_document,
        documents::ingest_document,
        documents::list_global,
        documents::upload_global,
        documents::get_global,
        documents::ingest_global,
        generate::generate_encounter,
        chat::chat,
        chat::chat_history,
        plot_hooks::list_plot_hooks,
        plot_hooks::create_plot_hook,
        plot_hooks::update_plot_hook,
        plot_hooks::delete_plot_hook,
        webhooks::list_webhooks,
        webhooks::create_webhook,
        webhooks::delete_webhook,
    ),
    components(
        schemas(
            Campaign, WorldState, CreateCampaignRequest, UpdateCampaignRequest,
            Character, AbilityScores, Backstory, PlotHook, HookPriority, CreateCharacterRequest, UpdateCharacterRequest, GenerateNpcRequest, CharacterType, Condition,
            TrackedPlotHook, PlotHookStatus, CreateTrackedPlotHookRequest, UpdateTrackedPlotHookRequest,
            CampaignWebhook, CreateWebhookRequest,
            Session, SessionEvent, SessionSummary, CreateSessionRequest, CreateSessionEventRequest, ImprovPromptResponse, Perspective,
            Encounter, CombatParticipant, ActionBudget, CreateEncounterRequest, AddParticipantRequest, UpdateParticipantRequest, EncounterStatus, EncounterSummary,
            CampaignDocument, GlobalDocument, DocumentKind, IngestionStatus, RankedChunk, DocSummary, MetaIndex,
            ChatMessage,
            generate::GenerateRequest, chat::ChatRequest,
            guide_core::models::GeneratedEncounter,
            guide_core::models::GameSystem,
            guide_core::models::EventType,
            guide_core::models::EventSignificance,
            guide_core::models::LoreType,
        )
    ),
    tags(
        (name = "The Guide", description = "DPM Campaign Management API")
    )
)]
pub struct ApiDoc;
